###################
# DISCORD OPTIONS #
###################

# The Discord bot token used to authenticate with the Discord API.
discord_token: null

# The Discord server in which to operate. Currently, the bot can only operate in one server.
discord_server: null

# The Discord channel(s) in which to service user commands. If empty, the bot will service user
# commands in all channels.
discord_command_channels: []

# The Discord channel(s) in which to broadcast. Each channel must also be configured with a
# list of which types of messages to broadcast. If the list is empty, all messages will be
# broadcast to that channel.
#   - "progression_items": Broadcast progression item sends.
#   - "useful_items": Broadcast useful item sends (includes progression).
#   - "all_items": Broadcast all item sends (includes useful and progression, excludes traps).
#   - "trap_items": Broadcast trap item sends.
#   - "death_links": Broadcast death link messages.
#   - "join_leave": Broadcast player join and leave messages.
#   - "player_chat": Broadcast when a player sends a chat message.
#   - "server_chat": Broadcast when the server sends a global chat message.
#   - "goal_reached": Broadcast when a player reaches their goal.
#   - "admin_alerts": Broadcast alerts related to bot status, like when it disconnects.
discord_broadcast_channels: {}


#########################
# MISCELLANEOUS OPTIONS #
#########################

# The directory in which to store persistent bot data, so the bot can be restarted. Files in
# this directory will be created per-room, so different rooms will not interfere with each other.
data_path: data

# The file containing custom death link messages, if desired. This file should be formatted
# with one message per line, where each line includes a {player} token that will be replaced
# with the name of the player who died.
death_link_messages_path: null

# The minimum logging level to record. Must be one of: "debug", "info", "warning", "error", "critical".
logging_level: info

# Whether to log to the console in brilliant colors.
logging_color: true
