################
# CORE OPTIONS #
################

# The Archipelago room to connect to. This is the identifier found after room/ in the URL
# of the room. For example, in https://archipelago.gg/room/93eBTEhDS_uu9-JsAl5YbQ, the room
# ID is "93eBTEhDS_uu9-JsAl5YbQ".
archipelago_room: null

# The Archipelago slot name to use when connecting. This can be any slot in the multiworld
# if you did not include ArchipelaDOS.yaml during generation.
archipelago_slot: ArchipelaDOS

# The Archipelago game to use when connecting. Change this to be the game corresponding to the
# archipelago_slot if you did not include ArchipelaDOS.yaml during generation.
archipelago_game: Archipelago

# The directory in which to store persistent bot data, so the bot can be restarted. Files in
# this directory will be created per-room, so different rooms will not interfere with each other.
data_path: data

# The file containing custom death link messages, if desired. This file should be formatted
# with one message per line, where each line includes a {player} token that will be replaced
# with the name of the player who died.
death_link_messages_path: null

# For some messages sent from Archipelago, a player name will be provided instead of a slot name
# or ID. This can happen for, say, death links from multiplayer games (like Minecraft, Raft),
# which may provide a particular player's name. This setting links a list of player names to a slot
# name, so that death links can be properly tracked per slot in these cases.
slot_players: {}


###################
# DISCORD OPTIONS #
###################

# The Discord bot token used to authenticate with the Discord API.
discord_token: null

# The Discord server in which to operate. Currently, the bot can only operate in one server.
discord_server: null

# The Discord channel(s) in which to service user commands. If empty, the bot will service user
# commands in all channels.
discord_command_channels: []

# The Discord channel(s) in which to broadcast. Each channel must also be configured with a
# list of which types of messages to broadcast. If the list is empty, all messages will be
# broadcast to that channel.
#   - "progression_items": Broadcast progression item sends.
#   - "useful_items": Broadcast useful item sends (includes progression).
#   - "all_items": Broadcast all item sends (includes useful and progression, excludes traps).
#   - "trap_items": Broadcast trap item sends.
#   - "death_links": Broadcast death link messages.
#   - "join_leave": Broadcast player join and leave messages.
#   - "player_chat": Broadcast when a player sends a chat message.
#   - "server_chat": Broadcast when the server sends a global chat message.
#   - "goal_reached": Broadcast when a player reaches their goal.
discord_broadcast_channels: {}


#########################
# LOCAL LOGGING OPTIONS #
#########################

# How the bot handles logging. Logs will always be printed to the console unless disabled.
#   - "none": Disables logging entirely.
#   - "console_only": Logs will only be printed to the console.
#   - "file_overwrite": Logs will be written to a file, overwriting it on each run.
#   - "file_append": Logs will be written to a file, appending to it on each run.
#   - "file_directory": Logs will be appended to a room-specific file in a directory.
logging_behavior: file_directory

# The path to the log file or directory, depending on the logging behavior.
logging_path: logs

# The minimum logging level to record. Must be one of: "debug", "info", "warning", "error", "critical".
logging_level: info

# Whether to log to the console in brilliant colors.
logging_color: true
